Repository rancher/rancher, pull requests merged in 2020-11, with the labels that each got.

#29455 Validation - Add proxy setup
  tests/validation/tests/v3_api/resource/squid/squid.conf
  tests/validation/tests/v3_api/test_proxy.py
Labels: area/validation-tests

#29912 Adding fixes for EKS v2 changes
  tests/validation/tests/v3_api/test_hosted_eks_cluster.py
Labels: setup/automation

#30071 [2.3] Handle rollback actions
  pkg/api/customization/multiclusterapp/multi_cluster_app.go
  pkg/api/customization/workload/workload.go
  pkg/api/store/workload/workload_store.go
  tests/integration/suite/test_multi_cluster_app.py
Labels: [zube]: Review

#30060 [2.4] Handle rollback actions
  pkg/api/customization/multiclusterapp/multi_cluster_app.go
  pkg/api/customization/workload/workload.go
  pkg/api/store/workload/workload_store.go
  tests/integration/suite/test_multi_cluster_app.py
Labels: [zube]: Review

#30189 Automation - stabilize backup/restore recover test
  tests/validation/tests/v3_api/common.py
  tests/validation/tests/v3_api/test_bkp_restore_s3_recover.py
Labels: setup/automation
