Repository rancher/rancher, pull requests merged in 2020-10, with the labels that each got.

#29281 Validation - Add Helm version param for tools
  tests/validation/Dockerfile.v3api
  tests/validation/tests/v3_api/scripts/build.sh
Labels: area/validation-tests

#29421 Adding k8s version for RKE cluster in a HA setup
  tests/validation/tests/v3_api/resource/cluster-ha.yml
  tests/validation/tests/v3_api/test_create_ha.py
Labels: setup/automation

#29425 Adding tests for v2 CIS scan run
  tests/validation/tests/v3_api/common.py
  tests/validation/tests/v3_api/test_v2_cis_scan.py
Labels: setup/automation

#29487 [Automation] - Cluster state fixes for the backup and recover scenario
  tests/validation/tests/v3_api/common.py
  tests/validation/tests/v3_api/test_bkp_restore_s3_recover.py
Labels: setup/automation

#29444 [2.5.2] Updated chart and tests to allow specify Rancher custom logos persistence
  chart/README.md
  chart/templates/deployment.yaml
  chart/templates/pvc.yaml
  chart/tests/deployment_test.yaml
  chart/tests/pvc_test.yaml
  chart/values.yaml
Labels: area/server-chart

#29443 Updated chart and tests to allow specify Rancher custom logos persistence
  chart/README.md
  chart/templates/deployment.yaml
  chart/templates/pvc.yaml
  chart/tests/deployment_test.yaml
  chart/tests/pvc_test.yaml
  chart/values.yaml
Labels: area/server-chart

#29765 Adding K8s version for import clusters
  tests/validation/tests/v3_api/resource/cluster.yml
  tests/validation/tests/v3_api/test_import_cluster.py
Labels: setup/automation
