Repository rancher/rancher, pull requests merged in 2021-09, with the labels that each got.

#33812 Automation - tag subnets with cluster name before creating EKS and ELB
  tests/validation/lib/aws.py
Labels: setup/automation

#34605 Validation - Copy latest changes from master to release/v2.6 branch
  tests/validation/tests/v3_api/resource/terraform/rke2/master/install_rke2_master.sh
  tests/validation/tests/v3_api/resource/terraform/rke2/master/instances_server.tf
  tests/validation/tests/v3_api/resource/terraform/rke2/master/join_rke2_master.sh
  tests/validation/tests/v3_api/resource/terraform/rke2/worker/instances_worker.tf
  tests/validation/tests/v3_api/resource/terraform/rke2/worker/join_rke2_agent.sh
  tests/validation/tests/v3_api/test_airgap.py
  tests/validation/tests/v3_api/test_custom_host_reg.py
Labels: area/validation-tests

#34859 Validation - Update jenkinsfile from `master` -> `release/v2.6`
  tests/validation/tests/v3_api/Jenkinsfile
  tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test
  tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_ontag
  tests/validation/tests/v3_api/Jenkinsfile_deploy_and_test_support_matrix
  tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests
  tests/validation/tests/v3_api/Jenkinsfile_provisioning_tests_ontag
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_custom_cluster_matrix
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_k3s_upgrade
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_provision_and_test
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade
Labels: setup/automation, area/validation-tests

#34829 [2.5] Update Steve version
  go.mod
  go.sum
Labels: status/auto-approved

#34787 Avoid a panic when a user adds a chart catalog containing a blank Helm chart
  pkg/api/norman/customization/catalog/store.go
Labels: priority/0, internal, [zube]: Review

#34906 Vendor bump for APIserver
  go.mod
  go.sum
Labels: status/auto-approved

#34907 [2.5] Vendor bump for APIserver
  go.mod
  go.sum
Labels: status/auto-approved

#34991 Update RKE to v1.3.1
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved
