Repository rancher/rancher, pull requests merged in 2021-11, with the labels that each got.

#35316 Updated test_upgrade to use sslip on 2.5.10+
  tests/validation/tests/v3_api/test_upgrade.py
Labels: setup/automation

#35303 Update dynamiclistener
  go.mod
  go.sum
Labels: status/auto-approved

#35434 Adding fixes for hardened local cluster
  tests/validation/tests/v3_api/resource/sysctl-config
Labels: setup/automation

#35429 add WS2022 LTSC, rm WS2004 sac, bump versions
  .drone.yml
  .gitattributes
  Dockerfile-windows.dapper
  Dockerfile.dapper
  go.mod
  go.sum
  manifest-agent-head.tmpl
  manifest-agent.tmpl
  package/windows/Dockerfile.agent
  pkg/agent/clean/cluster.go
  pkg/agent/clean/dupe_bindings.go
  pkg/agent/clean/node_notwindows.go
  pkg/agent/clean/orphan_bindings.go
  pkg/catalogv2/helmop/operation_test.go
  pkg/controllers/managementuserlegacy/logging/utils/syslog_unix.go
Labels: area/windows

#35473 [2.6.3] bump wrangler
  cmd/agent/main.go
  go.mod
  go.sum
  main.go
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#34667 [QA-Tests] Add and enhance airgap automation for k3s and rke2
  tests/validation/tests/v3_api/resource/airgap/registries.yaml
  tests/validation/tests/v3_api/scripts/configure.sh
  tests/validation/tests/v3_api/test_airgap.py
  tests/validation/tests/v3_api/test_k3s_airgap.py
  tests/validation/tests/v3_api/test_rke2_airgap.py
Labels: setup/automation

#35570 Remove windows plan placeholder
  pkg/controllers/provisioningv2/rke2/machinestatus/controller.go
Labels: area/windows, [zube]: Review

#35238 p0 test for AKS v2 hosted cluster
  tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py
  tests/validation/tests/v3_api/test_eks_v2_hosted_cluster.py
Labels: setup/automation
