Repository rancher/rancher, pull requests merged in 2021-04, with the labels that each got.

#31573 added support and examples for Rancher's new v1 API
  tests/validation/requirements_v3api.txt
  tests/validation/tests/common.py
  tests/validation/tests/v1_api/README.md
  tests/validation/tests/v1_api/__init__.py
  tests/validation/tests/v1_api/common.py
  tests/validation/tests/v1_api/resource/daemonset_1.json
  tests/validation/tests/v1_api/resource/deployment_1.json
  tests/validation/tests/v1_api/resource/fleet_1.json
  tests/validation/tests/v1_api/resource/monitoring_v2_values.json
  tests/validation/tests/v1_api/resource/namespace.yaml
  tests/validation/tests/v1_api/resource/project.yaml
  tests/validation/tests/v1_api/test_daemonset.py
  tests/validation/tests/v1_api/test_deployment.py
  tests/validation/tests/v1_api/test_fleet.py
  tests/validation/tests/v1_api/test_monitoring_v2.py
  tests/validation/tests/v3_api/common.py
Labels: area/validation-tests

#31034 Single click rke2-upgrade for jenkins
  tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_rke2_upgrade
  tests/validation/tests/v3_api/test_import_k3s_cluster.py
  tests/validation/tests/v3_api/test_import_rke2_cluster.py
  tests/validation/tests/v3_api/test_upgrade.py
Labels: setup/automation

#31759 Refactor GKE proxy
  pkg/api/norman/customization/gke/handler.go
  pkg/api/norman/customization/gke/listers.go
  pkg/multiclustermanager/capabilities/gke_capabilities.go
  pkg/multiclustermanager/capabilities/gke_machine_types_endpoint.go
  pkg/multiclustermanager/capabilities/gke_networks_endpoint.go
  pkg/multiclustermanager/capabilities/gke_service_accounts_endpoint.go
  pkg/multiclustermanager/capabilities/gke_subnetworks_endpoint.go
  pkg/multiclustermanager/capabilities/gke_version_endpoint.go
  pkg/multiclustermanager/capabilities/gke_zones_endpoint.go
  pkg/multiclustermanager/capabilities/http_request_body.go
  pkg/multiclustermanager/routes.go
Labels: [zube]: Review

#31894 [v2.5] Refactor GKE proxy
  pkg/api/norman/customization/gke/handler.go
  pkg/api/norman/customization/gke/listers.go
  pkg/multiclustermanager/capabilities/gke_capabilities.go
  pkg/multiclustermanager/capabilities/gke_machine_types_endpoint.go
  pkg/multiclustermanager/capabilities/gke_networks_endpoint.go
  pkg/multiclustermanager/capabilities/gke_service_accounts_endpoint.go
  pkg/multiclustermanager/capabilities/gke_subnetworks_endpoint.go
  pkg/multiclustermanager/capabilities/gke_version_endpoint.go
  pkg/multiclustermanager/capabilities/gke_zones_endpoint.go
  pkg/multiclustermanager/capabilities/http_request_body.go
  pkg/multiclustermanager/routes.go
Labels: [zube]: Review

#31944 Validation - Update test image repo
  tests/validation/tests/rke/resources/k8s_templates/validation.yml.j2
  tests/validation/tests/rke/resources/k8s_ymls/service_k8test1.yml
  tests/validation/tests/rke/resources/k8s_ymls/single_pod.yml
  tests/validation/tests/rke/resources/k8s_ymls/two_container_pod.yaml
  tests/validation/tests/v1_api/common.py
  tests/validation/tests/v3_api/common.py
Labels: area/validation-tests
