Repository rancher/rancher, pull requests merged in 2022-03, with the labels that each got.

#36718 Automation - fix test of etcd backup create for RKE1 clusters
  tests/validation/tests/v3_api/common.py
  tests/validation/tests/v3_api/test_bkp_restore_local.py
Labels: setup/automation

#36787 bump to rancher/machine v0.15.0-rancher80
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/settings/setting.go
Labels: area/machine, [zube]: Review

#36828 [Automation] - use gp3 as default volume type for ec2 instances
  tests/validation/lib/aws.py
Labels: setup/automation

#36850 add mkisofs to rancher image and jailer.sh
  package/Dockerfile
  package/jailer.sh
Labels: area/rke, area/vsphere, bug

#36771 fix formatting issues in wins install script
  pkg/controllers/provisioningv2/rke2/bootstrap/controller_test.go
  pkg/provisioningv2/rke2/installer/installer.go
  pkg/provisioningv2/rke2/installer/installer_test.go
Labels: area/windows, [zube]: Review, status/release-blocker

#36911 go mod vendor
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
  vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go
  vendor/modules.txt
Labels: status/auto-approved

#36913 bump rke to fix kube-scheduler authentication kubecfg for 1.23
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36927 fix mkisofs jailer path
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  package/jailer.sh
  pkg/settings/setting.go
Labels: status/final-release-blocker

#36949 update rke to address coredns mirror update
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36957 Automation - adding_k8s_version parameter for local HA Airgap cluster
  tests/validation/tests/v3_api/test_airgap_ha.py
Labels: setup/automation

#36965 pinning v1.3.8-rc10 of rke
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37006 bump rke to v1.3.8-rc11
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37014 bumped eks,aks, and gke operator to latest rc
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37018 bump aks, eks, and gke operators
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37012 Upgrade steve version
  go.mod
  go.sum
Labels: status/auto-approved

#37083 Upgrading version of rancher/go-client to fix upstream issue
  go.mod
  go.sum
Labels: status/auto-approved

#37101 Removing PowerShell from RKE2 custom registration command.
  pkg/controllers/dashboard/clusterregistrationtoken/status.go
Labels: area/windows, area/provisioning-v2, feature/provisioned-rke2-k3s, team/area4, feature/provision-rke2-k3s

#37098 Updating the instructions to handle Windows and PowerShell
  pkg/provisioningv2/rke2/planner/instructions.go
  pkg/provisioningv2/rke2/planner/instructions_test.go
Labels: area/windows

#37055 [v2.6.4] final rc bumps
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/settings/setting.go
  scripts/package
Labels: status/auto-approved

#37125 Tick UI Dashboard index to release-2.6.3-patch3
  package/Dockerfile
  pkg/settings/setting.go
Labels: [zube]: Review
