Repository rancher/rancher, pull requests merged in 2022-04, with the labels that each got.

#37270 Update lasso
  go.mod
  go.sum
Labels: status/auto-approved

#37261 [release/v2.6] go generate
  pkg/apis/provisioning.cattle.io/v1/zz_generated_deepcopy.go
Labels: status/auto-approved

#37259 Update remotedialer
  go.mod
  go.sum
  pkg/api/norman/customization/monitor/prometheus_manager.go
Labels: status/auto-approved

#37258 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#37294 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#37314 [PR] Fixed fleet min version on rancher upgrade
  package/Dockerfile
Labels: area/fleet, team/area3

#37356 Update rke tag
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37354 [2.5] Bump steve for panic fix
  go.mod
  go.sum
Labels: status/auto-approved

#37358 [release/v2.6] Bump RKE to v1.3.10-rc3
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37367 pin v1.2.19 rke
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37375 Bump steve
  go.mod
  go.sum
Labels: status/auto-approved

#37425 Version bump
  cmd/rancherd/go.mod
  cmd/rancherd/go.sum
  go.mod
  go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/auto-approved

#37427 Ensure that Rancher serves the right Windows install script when airgapped
  pkg/provisioningv2/rke2/installer/installer.go
  pkg/provisioningv2/rke2/installer/server_test.go
Labels: area/windows, area/air-gapped

#37463 [release/v2.6] Bump RKE to v1.3.10-rc5
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#37484 bump csi proxy version for 2022 support
  package/Dockerfile
Labels: kind/bug-qa, [zube]: Review, team/area4

#37496 Going to try to skip Windows since it doesn't run a cluster agent.
  pkg/provisioningv2/rke2/planner/etcdrestore.go
  pkg/provisioningv2/rke2/planner/planner.go
  pkg/provisioningv2/rke2/planner/planner_test.go
Labels: area/windows, team/area4

#37532 fix v1 monitoring app panic
  pkg/controllers/managementuserlegacy/alert/deployer/upgradeimpl.go
Labels: area/windows, [zube]: Review, status/release-blocker, team/area4
