Repository rancher/rancher, pull requests merged in 2022-06, with the labels that each got.

#37892 Fix missing entry in go.sum for aks-operator
  go.sum
Labels: alpha-priority/0, status/auto-approved

#37891 Revert "Scope Drone steps depending on push to branch/tag"
  .drone.yml
Labels: alpha-priority/0

#37924 Ensure password has quotes for proxy
  tests/validation/tests/v3_api/test_proxy.py
Labels: status/auto-approved

#37985 Bump steve for new watch changes
  go.mod
  go.sum
Labels: status/auto-approved

#37989 [2.5] Bump steve for new watch changes
  go.mod
  go.sum
Labels: status/auto-approved

#38041 updates norman and apiserver to the latest version.
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/auto-approved

#38093 Bump remotedialer for pause/resume fix
  go.mod
  go.sum
Labels: status/auto-approved

#38099 [2.5.15] Bump remotedialer for pause/resume fix
  go.mod
  go.sum
Labels: status/auto-approved

#38098 [2.5] Bump remotedialer for pause/resume fix
  go.mod
  go.sum
Labels: status/auto-approved

#38091 Bump lasso version
  go.mod
  go.sum
  pkg/apis/catalog.cattle.io/v1/zz_generated_deepcopy.go
  pkg/apis/cluster.cattle.io/v3/zz_generated_deepcopy.go
  pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
  pkg/apis/project.cattle.io/v3/zz_generated_deepcopy.go
Labels: status/auto-approved

#38100 Bump aks operator version to v1.0.6-rc3
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38096 [2.6.6] Bump remotedialer for pause/resume fix
  go.mod
  go.sum
Labels: status/auto-approved

#38103 disable harvester node driver in drone prov tests
  scripts/run
Labels: kind/ci-improvements

#38145 Update `gopkg.in/yaml.v3` minor version
  cmd/rancherd/go.mod
  cmd/rancherd/go.sum
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/auto-approved

#38151 Update RKE
  go.mod
  go.sum
Labels: status/auto-approved
