Repository rancher/rancher, pull requests merged in 2022-01, with the labels that each got.

#35997 Update Steve
  go.mod
  go.sum
Labels: status/auto-approved

#36020 Bump remotedialer to add pause/resume functionality
  go.mod
  go.sum
Labels: status/auto-approved

#36019 Bump remotedialer to add wait/resume functionality
  go.mod
  go.sum
Labels: status/auto-approved

#35959 [2.5] Update default ui-dashboard-index setting
  pkg/settings/setting.go
Labels: team/ui, [zube]: Review

#36075 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36076 Bump rke for fix where addon jobs are stuck in removing
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36077 [Backport v2.5] Bump rke for fix where addon jobs are stuck in removing
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36078 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36127 [2.5] fix issue with 2004SAC missing from manifest
  .drone.yml
  Dockerfile-windows-1809.dapper
  Dockerfile-windows-2004.dapper
  Dockerfile-windows-20H2.dapper
Labels: area/windows

#36175 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36200 Automation - rebuilt ubuntu-18.04 for validation tests
  tests/validation/lib/aws.py
Labels: setup/automation

#36206 [2.5] Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36207 Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36205 [2.6.3] Update remotedialer
  go.mod
  go.sum
Labels: status/auto-approved

#36194 Automation - Bumping the upstream Dockerimage version to python:3.7.12 for validation tests
  tests/validation/Dockerfile.v3api
Labels: setup/automation

#36246 Update tags for v2.5.12-rc7
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36080 Update steve, wrangler, apiserver, and norman
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved
