Repository rancher/rancher, pull requests merged in 2022-02, with the labels that each got.

#36378 v2.6.4-rc2
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#36431 Bump the Docker CLI dependency version to v20.10.9
  go.mod
  go.sum
Labels: status/auto-approved

#36436 Bump kube-api-auth version
  pkg/apis/management.cattle.io/v3/tools_system_images.go
Labels: team/area1

#36367 Add restricted-noroot PSP policy to match upstream Kubernetes restricted PSP
  pkg/data/management/podsecuritypolicytemplate_data.go
Labels: release-note, team/area1

#36312 Remove unused Thrift direct dependency
  go.mod
Labels: status/auto-approved, team/area1

#35582 Add multi-os support to v2prov rke2 clusters
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/api/norman/customization/vsphere/getters.go
  pkg/api/norman/customization/vsphere/getters_test.go
  pkg/api/norman/customization/vsphere/handler.go
  pkg/apis/provisioning.cattle.io/v1/rke.go
  pkg/controllers/provisioningv2/rke2/bootstrap/controller.go
  pkg/controllers/provisioningv2/rke2/bootstrap/controller_test.go
  pkg/controllers/provisioningv2/rke2/common.go
  pkg/controllers/provisioningv2/rke2/dynamicschema/dynamicschema.go
  pkg/controllers/provisioningv2/rke2/machineprovision/args.go
  pkg/controllers/provisioningv2/rke2/provisioningcluster/template.go
  pkg/settings/setting.go
Labels: area/windows, [zube]: Review, feature/rancher-machine, team/area4

#36553 add wins install script for rancher airgap
  package/Dockerfile
Labels: area/windows, kind/bug-qa, [zube]: Review, status/release-blocker

#36636 add extra plan sync prior to setting the machineJoinURL
  pkg/provisioningv2/rke2/planner/store.go
Labels: kind/bug-qa, area/provisioning-v2

#36676 Bump eks and aks operator versions
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved
