Repository rancher/rancher, pull requests merged in 2022-07, with the labels that each got.

#38158 Update ui version to v2.6.7-rc1
  package/Dockerfile
Labels: status/auto-approved

#38157 Update aks/eks/gke operators
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38241 Bump aks operator to version v1.0.6
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38275 Update aws-iam-authenticator to v0.5.9 from Rancher's fork
  go.mod
  go.sum
Labels: status/auto-approved

#38290 Bump norman and apiserver versions
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/go.mod
  pkg/client/go.sum
Labels: status/auto-approved

#38295 update rke to v1.3.13-rc4
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/client/generated/management/v3/zz_generated_aci_network_provider.go
Labels: status/auto-approved

#38298 Bump eks operator to version v1.1.4-rc3
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38101 introduce version restriction for k3s upgrade images starting with 1.21.0
  pkg/image/export/main.go
Labels: kind/bug

#38310 Automation caused a merged conflict.
  package/Dockerfile
Labels: status/auto-approved

#38316 Replace all invalid characters for v2prov snapshots with -
  pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go
  pkg/controllers/provisioningv2/rke2/plansecret/plansecret.go
Labels: area/etcd, area/provisioning-v2

#38363 bump eks operator to version v1.1.4-rc4
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38387 Fleet update to 0.3.10-rc5
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38399 Add missing go generate changes
  pkg/apis/management.cattle.io/v3/zz_generated_deepcopy.go
  pkg/client/generated/management/v3/zz_generated_catalog.go
  pkg/client/generated/management/v3/zz_generated_catalog_secrets.go
  pkg/client/generated/management/v3/zz_generated_catalog_spec.go
  pkg/client/generated/management/v3/zz_generated_cluster.go
  pkg/client/generated/management/v3/zz_generated_cluster_catalog.go
  pkg/client/generated/management/v3/zz_generated_cluster_secrets.go
  pkg/client/generated/management/v3/zz_generated_cluster_spec.go
  pkg/client/generated/management/v3/zz_generated_cluster_spec_base.go
  pkg/client/generated/management/v3/zz_generated_project_catalog.go
Labels: status/auto-approved

#38398 Update for v2.5.16 RC1
  go.mod
  go.sum
  package/Dockerfile
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#38430 Bump UI tags to v2.6.7-rc4
  package/Dockerfile
Labels: status/auto-approved

#38469 Bump dynamiclistener
  go.mod
  go.sum
Labels: status/auto-approved
