Repository rancher/rancher, pull requests merged in 2023-01, with the labels that each got.

#40053 bump tags for UI and CLI to v2.7.2-rc1
  package/Dockerfile
Labels: status/auto-approved

#40031 Windows Custom Cluster Automation
  tests/framework/clients/ec2/client.go
  tests/framework/clients/ec2/config.go
  tests/framework/extensions/nodes/ec2/ec2.go
  tests/v2/validation/provisioning/config.go
  tests/v2/validation/provisioning/nodeproviders.go
  tests/v2/validation/provisioning/rke2/README.md
  tests/v2/validation/provisioning/rke2/custom_cluster_test.go
Labels: team/area2, area/automation-test

#40064 [v2.6 Backport] Windows Custom Cluster Automation
  tests/framework/clients/ec2/client.go
  tests/framework/clients/ec2/config.go
  tests/framework/extensions/nodes/ec2/ec2.go
  tests/v2/validation/provisioning/config.go
  tests/v2/validation/provisioning/nodeproviders.go
  tests/v2/validation/provisioning/rke2/README.md
  tests/v2/validation/provisioning/rke2/custom_cluster_test.go
Labels: team/area2, area/automation-test

#40151 Bump steve version
  go.mod
  go.sum
Labels: status/auto-approved

#40186 Modified existing tests to reflect changes to NodeCreationFunc
  tests/v2/validation/provisioning/k3s/custom_cluster_test.go
  tests/v2/validation/provisioning/rke1/custom_cluster_test.go
Labels: area/automation-test

#40187 Modified existing tests to reflect changes to NodeCreationFunc
  tests/v2/validation/provisioning/k3s/custom_cluster_test.go
  tests/v2/validation/provisioning/rke1/custom_cluster_test.go
Labels: area/automation-test

#40185 [v2.7] update rke to v1.4.3-rc4
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/apis/rke.cattle.io/v1/zz_generated_deepcopy.go
  pkg/client/generated/management/v3/zz_generated_cloud_provider.go
Labels: status/auto-approved

#40238 Bump steve and apiserver
  go.mod
  go.sum
Labels: status/auto-approved

#40278 update rke to v1.3.18
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#40158 [release/v2.7] Bump aks-operator version to v1.1.0-rc4
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/kontainer-engine/drivers/aks/aks_driver.go
Labels: status/auto-approved

#40287 [2.6] Update UI tag
  package/Dockerfile
Labels: status/auto-approved

#40314 run go generate
  pkg/client/generated/management/v3/zz_generated_aks_node_pool.go
Labels: status/auto-approved
