Repository rancher/rancher, pull requests merged in 2023-03, with the labels that each got.

#40746 [v2.7] update rke to v1.4.4-rc2
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#40793 Unrc aks operator to v1.0.9
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#40693 Ignore obj being as helm release obj if data is too small
  pkg/catalogv2/helm/helm3.go
Labels: team/mapps

#40846 [dev-v2.7] Bump aks-operator to rc6
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#40906 [dev-2.7] Bump aks-operator to 102.0.0+up1.1.0-rc7
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#40933 Add cattle-elemental-system to list of system namespaces
  pkg/settings/setting.go
Labels: area/backup-recover

#40955 Update Google Provider version in gke.tf
  tests/validation/tests/v3_api/resource/terraform/gke/gke.tf
Labels: area/automation-test

#40965 Update Google Provider version in gke.tf
  tests/validation/tests/v3_api/resource/terraform/gke/gke.tf
Labels: area/automation-test

#40997 Update norman
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved
