Repository rancher/rancher, pull requests merged in 2023-09, with the labels that each got.

#42622 [2.7] Update EKS operator to v1.2.2-rc6
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42694 [2.8] Update gke-operator to v1.2.0-rc1
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42695 [2.8] Update eks-operator to v1.3.0-rc2
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42589 Update the readme with some useful information
  tests/integration/README.md
Labels: documentation

#42405 verifying generated fields are removed
  tests/framework/clients/rancher/v1/client.go
  tests/framework/extensions/configmaps/configmaps.go
  tests/v2/validation/configmaps/generatedfields.go
  tests/v2/validation/configmaps/generatedfields_test.go
Labels: area/automation-framework, area/automation-test

#42090 GRB, CRTB, PRTB validation for GH781
  tests/v2/validation/rbac/rbac_test.go
Labels: area/automation-test

#42805 bump rke to v1.4.10-rc2
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42829 Bump CLI version to v2.7.7-rc2
  package/Dockerfile
  tests/v2/codecoverage/package/Dockerfile
Labels: status/auto-approved

#41846 [v2.7] Add support for deleting clusters and scaling RKE2/K3S machinepools
  tests/framework/extensions/clusters/clusters.go
  tests/framework/extensions/machinepools/machinepools.go
  tests/framework/extensions/nodes/node_status.go
  tests/framework/extensions/provisioning/verify.go
  tests/framework/extensions/rke1/nodepools/nodepools.go
  tests/framework/extensions/scalinginput/config.go
  tests/framework/extensions/workloads/pods/verify.go
  tests/v2/validation/deleting/README.md
  tests/v2/validation/deleting/delete_cluster_k3s_test.go
  tests/v2/validation/deleting/delete_cluster_rke1_test.go
  tests/v2/validation/deleting/delete_cluster_rke2_test.go
  tests/v2/validation/nodescaling/README.md
  tests/v2/validation/nodescaling/replace.go
  tests/v2/validation/nodescaling/scale_replace_rke1_test.go
  tests/v2/validation/nodescaling/scale_replace_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_k3s_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_rke2_test.go
  tests/v2/validation/nodescaling/scaling_nodepools.go
  tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
  tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
  tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
  tests/v2/validation/provisioning/registries/registry_test.go
  tests/v2/validation/provisioning/rke1/README.md
  tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
Labels: area/automation-framework, area/automation-test

#42515 [v2.8] Add support for deleting clusters and scaling RKE2/K3S machinepools
  tests/framework/extensions/clusters/clusters.go
  tests/framework/extensions/machinepools/machinepools.go
  tests/framework/extensions/nodes/node_status.go
  tests/framework/extensions/provisioning/verify.go
  tests/framework/extensions/rke1/nodepools/nodepools.go
  tests/framework/extensions/scalinginput/config.go
  tests/framework/extensions/workloads/pods/verify.go
  tests/v2/validation/deleting/README.md
  tests/v2/validation/deleting/delete_cluster_k3s_test.go
  tests/v2/validation/deleting/delete_cluster_rke1_test.go
  tests/v2/validation/deleting/delete_cluster_rke2_test.go
  tests/v2/validation/nodescaling/README.md
  tests/v2/validation/nodescaling/replace.go
  tests/v2/validation/nodescaling/scale_replace_rke1_test.go
  tests/v2/validation/nodescaling/scale_replace_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_k3s_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_rke1_test.go
  tests/v2/validation/nodescaling/scaling_node_driver_rke2_test.go
  tests/v2/validation/nodescaling/scaling_nodepools.go
  tests/v2/validation/provisioning/airgap/k3s_custom_cluster_test.go
  tests/v2/validation/provisioning/airgap/rke2_custom_cluster_test.go
  tests/v2/validation/provisioning/hostnametruncation/hostname_truncation_test.go
  tests/v2/validation/provisioning/registries/registry_test.go
  tests/v2/validation/provisioning/rke1/README.md
  tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
Labels: area/automation-framework, area/automation-test

#42879 [2.8] Update eks-operator to v1.3.0-rc3
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42882 [2.8] Update aks-operator to v1.2.0-rc4
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42984 bump rke to v1.5.0-rc8
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved

#42994 update dynamiclistener to v0.3.6
  go.mod
  go.sum
Labels: status/auto-approved

#42980 Fix "unknown revision v0.0.0" error caused by the k8s.io/kubernetes module
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: status/auto-approved
