Repository rancher/rancher, pull requests merged in 2024-10, with the labels that each got.

#45266 [v2.9] Added proxied rancher provisioning tests
  go.mod
  go.sum
  tests/v2/actions/clusters/clusterconfig.go
  tests/v2/actions/clusters/clusters.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/actions/provisioninginput/config.go
  tests/v2/validation/provisioning/proxy/README.md
  tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/proxy.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
Labels: status/stale, area/automation-test, area/jenkins

#45267 [v2.8] Added proxied rancher provisioning tests
  go.mod
  go.sum
  tests/v2/actions/clusters/clusterconfig.go
  tests/v2/actions/clusters/clusters.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/actions/provisioninginput/config.go
  tests/v2/validation/provisioning/proxy/README.md
  tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/proxy.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
Labels: status/stale

#45293 [v2.7] Added proxied rancher provisioning tests
  go.mod
  go.sum
  tests/v2/actions/clusters/clusterconfig.go
  tests/v2/actions/clusters/clusters.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/actions/provisioninginput/config.go
  tests/v2/validation/provisioning/proxy/README.md
  tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/k3s_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/proxy.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke1_proxy_node_driver_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_custom_cluster_test.go
  tests/v2/validation/provisioning/proxy/rke2_proxy_node_driver_test.go
Labels: status/stale

#47261 [main] P0 Project Container Default Resource Limit tests
  tests/v2/actions/projects/projects.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
Labels: automation-enhancement

#47341 <main> Converted test_wl_pause_orchestration from python to go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
  tests/validation/tests/v3_api/test_workload.py
Labels: team/pit-crew

#45734 P0 Project Resource Quota tests
  tests/v2/actions/projects/projects.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/projects/projects_resource_quota_test.go
Labels: automation-enhancement

#47279 [Main] Migrating configmaps tests from python to go
  tests/v2/actions/configmaps/configmaps.go
  tests/v2/validation/rbac/configmaps/README.md
  tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
Labels: team/pit-crew

#47342 <v2.7> Converted test_wl_pause_orchestration from python to go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
  tests/validation/tests/v3_api/test_workload.py
Labels: team/pit-crew

#47344 <v2.9> Converted test_wl_pause_orchestration from python to go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
  tests/validation/tests/v3_api/test_workload.py
Labels: team/pit-crew

#47343 <v2.8> Converted test_wl_pause_orchestration from python to go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
  tests/validation/tests/v3_api/test_workload.py
Labels: team/pit-crew

#47447 Adding VerifyRoleBindingsForUser to rbac_test
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/rbac/verify.go
  tests/v2/validation/rbac/rbac_test.go
Labels: area/automation-framework, area/automation-test

#47448 [v2.9] Adding VerifyRoleBindingsForUser to rbac_test
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/rbac/verify.go
  tests/v2/validation/rbac/rbac_test.go
Labels: area/automation-framework, area/automation-test

#47449 [v2.8] Added VerifyRoleBindingsForUser to rbac_test
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/rbac/verify.go
  tests/v2/validation/rbac/rbac_test.go
Labels: area/automation-framework, area/automation-test

#47451 [v2.7]Added VerifyRoleBindingsForUser to rbac_test
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/rbac/verify.go
  tests/v2/validation/rbac/rbac_test.go
Labels: area/automation-framework, area/automation-test

#47484 Removed forward slashes from the tests (#47474)
  tests/v2/validation/auth/userretention/userretention_disable_user_test.go
  tests/v2/validation/auth/userretention/userretention_settings_test.go
Labels: area/automation-test

#47303 Fleet + snapshot & restore tests
  go.mod
  go.sum
  tests/v2/actions/etcdsnapshot/creates.go
  tests/v2/actions/etcdsnapshot/etcdsnapshot.go
  tests/v2/actions/etcdsnapshot/verify.go
  tests/v2/actions/provisioning/verify.go
  tests/v2/actions/scalinginput/replace.go
  tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go
  tests/v2/validation/fleet/public_gitrepo_test.go
  tests/v2/validation/fleet/snapshot/README.md
  tests/v2/validation/fleet/snapshot/snapshot_restore_existing_gitrepo_test.go
  tests/v2/validation/nodescaling/auto_replace_test.go
  tests/v2/validation/nodescaling/scale_replace_rke1_test.go
  tests/v2/validation/nodescaling/scale_replace_test.go
  tests/v2/validation/provisioning/rke1/provisioning_node_driver_test.go
  tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go
  tests/v2/validation/snapshot/snapshot.go
  tests/v2/validation/snapshot/snapshot_additional_test.go
  tests/v2/validation/snapshot/snapshot_restore_k8s_upgrade_test.go
  tests/v2/validation/snapshot/snapshot_restore_test.go
  tests/v2/validation/snapshot/snapshot_restore_upgrade_strategy_test.go
  tests/v2/validation/snapshot/snapshot_restore_wins_test.go
  tests/v2/validation/snapshot/snapshot_retention_test.go
Labels: team/pit-crew

#47256 Migrating rke1 templates test from python to go
  tests/v2/actions/clustertemplates/clustertemplates.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/README.md
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
Labels: team/pit-crew

#47478 <main> Improving workloads tests
  tests/v2/actions/workloads/pods/pods.go
  tests/v2/validation/workloads/deployment_test.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
Labels: team/pit-crew

#46740 Add network policy connectivity tests
  tests/v2/validation/networking/README.md
  tests/v2/validation/networking/connectivity/network_policy.go
  tests/v2/validation/networking/connectivity/network_policy_test.go
  tests/validation/tests/v3_api/test_network_policy.py
Labels: team/pit-crew

#47038 [CHART] Support additional taints tolerations
  chart/templates/deployment.yaml
  chart/tests/deployment_test.yaml
  chart/values.yaml
Labels: team/observability&backup

#47476 [main] P0 tests for GH45811
  tests/v2/actions/kubeapi/rbac/list.go
  tests/v2/validation/rbac/fleetworkspaces/README.md
  tests/v2/validation/rbac/fleetworkspaces/fleetworkspaces.go
  tests/v2/validation/rbac/fleetworkspaces/fleetworkspaces_test.go
Labels: area/automation-test

#47674 [main] P0 Project RBAC Tests
  tests/v2/actions/workloads/daemonset/daemonset.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_rbac_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
  tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
  tests/v2/validation/rbac/secrets/rbac_secrets_test.go
  tests/v2/validation/workloads/deployment_test.go
  tests/v2/validation/workloads/workload_test.go
Labels: area/automation-test

#47676 [v2.8] P0 Project RBAC Tests
  tests/v2/actions/workloads/daemonset/daemonset.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_rbac_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
  tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
  tests/v2/validation/rbac/secrets/rbac_secrets_test.go
  tests/v2/validation/workloads/workload_test.go
Labels: area/automation-test

#46095 P0 Project RBAC and Additional tests
  tests/v2/actions/workloads/daemonset/daemonset.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_rbac_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
  tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
  tests/v2/validation/rbac/secrets/rbac_secrets_test.go
  tests/v2/validation/workloads/workload_test.go
Labels: automation-enhancement

#47482 <v2.7> Improving workloads tests
  tests/v2/actions/workloads/pods/pods.go
  tests/v2/validation/workloads/deployment_test.go
  tests/v2/validation/workloads/workload.go
  tests/v2/validation/workloads/workload_test.go
Labels: team/pit-crew

#47526 [2.8] Migrating rke templates tests from python to go
  go.mod
  go.sum
  tests/v2/actions/clustertemplates/clustertemplates.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/README.md
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go
Labels: team/pit-crew

#47529 [2.9] Migrating rke templates tests from python to go
  go.mod
  go.sum
  tests/v2/actions/clustertemplates/clustertemplates.go
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/README.md
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/provisioning/provisioning_clustertemplate_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/rbac/snapshotrbac/snapshot_rbac_test.go
Labels: team/pit-crew

#47755 [2.8] Fix timeout issue in project tests
  tests/v2/actions/projects/projects.go
  tests/v2/validation/projects/projects.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
Labels: automation-fix

#47741 [2.9] Fix timeout issue in project tests
  tests/v2/actions/projects/projects.go
  tests/v2/validation/projects/projects.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
Labels: automation-fix

#47754 [main] Fix timeout issue in project tests
  tests/v2/actions/projects/projects.go
  tests/v2/validation/projects/projects.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
Labels: automation-fix

#47634 [main] P0 tests for GH47000
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/workloads/daemonset/daemonset.go
  tests/v2/validation/rbac/clusterandprojectroles/manage_workloads_role_test.go
Labels: area/automation-test
