Repository rancher/rancher, pull requests merged in 2024-01, with the labels that each got.

#43940 [Backport 2.7] Bump rancher/machine image to pull in changes for ubuntuSystemd provisioner fix
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/settings/setting.go
  tests/v2/codecoverage/package/Dockerfile
Labels: area/machine, area/provisioning-rke1, team/area2

#43939 Bump rancher/machine image to pull in changes for ubuntuSystemd provisioner fix
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/settings/setting.go
  tests/v2/codecoverage/package/Dockerfile
Labels: area/machine, area/provisioning-rke1, team/area2

#43938 [Forwardport 2.9] Bump rancher/machine image to pull in changes for ubuntuSystemd provisioner fix
  Dockerfile.dapper
  go.mod
  go.sum
  package/Dockerfile
  pkg/settings/setting.go
  tests/v2/codecoverage/package/Dockerfile
Labels: kind/bug, area/machine, area/provisioning-rke1, team/area2

#43881 [v2.8] Allow import EKS cluster with self-managed nodes
  pkg/controllers/management/eks/eks_cluster_handler.go
Labels: kind/bug, JIRA

#44150 Git ssh custom port [Backport - relase/v2.7]
  pkg/catalogv2/git/download.go
  pkg/catalogv2/git/download_test.go
  pkg/catalogv2/git/git.go
  pkg/catalogv2/git/utils.go
  pkg/catalogv2/git/utils_test.go
Labels: team/mapps

#44194 fixing by testing only small fork
  tests/v2/integration/catalogv2/rancher_managed_charts_test.go
Labels: team/mapps

#44196 fixing by testing only small fork - [Forwardport to 2.9]
  tests/v2/integration/catalogv2/rancher_managed_charts_test.go
Labels: team/mapps

#44238 [v2.8] chore: improve error message when eks cluster does not have nodes
  pkg/controllers/management/eks/eks_cluster_handler.go
Labels: kind/chore
