Repository rancher/rancher, pull requests merged in 2024-12, with the labels that each got.

#48106 [main] RBAC registry secret tests
  tests/v2/actions/secrets/config.go
  tests/v2/actions/secrets/secrets.go
  tests/v2/actions/secrets/template.go
  tests/v2/actions/workloads/daemonset/daemonset.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/projects/projects_container_default_resource_limit_test.go
  tests/v2/validation/projects/projects_resource_quota_test.go
  tests/v2/validation/projects/projects_test.go
  tests/v2/validation/rbac/clusterandprojectroles/manage_workloads_role_test.go
  tests/v2/validation/rbac/configmaps/configmaps_rbac_test.go
  tests/v2/validation/rbac/secrets/README.md
  tests/v2/validation/rbac/secrets/rbac_opaque_secrets_test.go
  tests/v2/validation/rbac/secrets/rbac_registry_secrets_test.go
  tests/v2/validation/rbac/secrets/rbac_secrets_test.go
  tests/v2/validation/workloads/deployment_test.go
  tests/v2/validation/workloads/workload_test.go
Labels: area/automation-test

#44854 fix-user-cluster.yml
  cleanup/user-cluster.yml
Labels: status/stale

#48246 <main> Investigate recurring run failures in Workloads tests
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
Labels: team/pit-crew

#48245 <v2.9> Investigate recurring run failures in Workloads tests
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
Labels: team/pit-crew

#48247 <2.8> Investigate recurring run failures in Workloads tests
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
Labels: team/pit-crew

#46672 Allow to disable fleet cluster provisioning via provisioning.cattle.io/externally-managed annotation
  pkg/controllers/provisioningv2/cluster/controller.go
  pkg/controllers/provisioningv2/cluster/controller_test.go
  pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
  pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
Labels: kind/enhancement

#46877 [SURE-5388]: add owner reference to the secret
  pkg/controllers/management/cluster/clustercontroller.go
  pkg/controllers/management/clusterprovisioner/provisioner.go
  pkg/controllers/management/clusterprovisioner/store.go
  pkg/controllers/management/drivers/kontainerdriver/kontainerdriver.go
  pkg/controllers/management/etcdbackup/etcdbackup.go
  pkg/controllers/managementuser/certsexpiration/certsexpiration.go
  pkg/encryptedstore/secrets_store.go
  pkg/nodeconfig/config.go
  pkg/rkenodeconfigserver/lookup.go
Labels: team/hostbusters, squad/BRO

#48536 <main> Add PNI, k3s cloud manager validations and refactor for port tests
  tests/v2/validation/networking/connectivity/network_policy.go
  tests/v2/validation/networking/connectivity/port_test.go
Labels: team/pit-crew

#48451 <v2.9> Add PNI, k3s cloud manager validations and refactor for port tests
  tests/v2/validation/networking/connectivity/network_policy.go
  tests/v2/validation/networking/connectivity/network_policy_test.go
  tests/v2/validation/networking/connectivity/port_test.go
Labels: team/pit-crew

#48452 <v2.8> Add PNI, k3s cloud manager validations and refactor for port tests
  tests/v2/validation/networking/connectivity/network_policy.go
  tests/v2/validation/networking/connectivity/network_policy_test.go
  tests/v2/validation/networking/connectivity/port_test.go
Labels: team/pit-crew
