Repository rancher/rancher, pull requests merged in 2025-04, with the labels that each got.

#49537 [2.11][chart] Add new options for Rancher default service hardening
  chart/templates/extra-manifests.yaml
  chart/templates/ingress.yaml
  chart/templates/service.yaml
  chart/tests/ingress_test.yaml
  chart/tests/service_test.yaml
  chart/values.schema.json
  chart/values.yaml
Labels: team/observability&backup

#49637 ext tokens: added handling of finalizers and ownerref
  pkg/auth/providerrefresh/refresher_test.go
  pkg/auth/requests/authenticate_test.go
  pkg/auth/requests/impersonate_test.go
  pkg/controllers/management/auth/user_test.go
  pkg/ext/stores/tokens/tokens.go
  pkg/ext/stores/tokens/tokens_test.go
  pkg/ext/stores/useractivity/store_test.go
Labels: team/collie

#49616 fix garbage collection broken by ext tokens?
  pkg/ext/stores/tokens/tokens.go
  pkg/ext/stores/tokens/tokens_test.go
  pkg/ext/stores/tokens/zz_token_fakes.go
Labels: area/kubernetes, team/collie

#49638 ext token ttl mishandling of edge cases when comparing
  pkg/apis/ext.cattle.io/v1/types.go
  pkg/ext/stores/tokens/tokens.go
  pkg/ext/stores/tokens/tokens_test.go
  pkg/generated/openapi/zz_generated_openapi.go
Labels: team/collie
