Repository rancher/rancher, pull requests merged in 2025-08, with the labels that each got.

#51310 [backport 2.12] move more complex signers to own files
  pkg/httpproxy/sign.go
  pkg/httpproxy/signer_awsv4.go
  pkg/httpproxy/signer_digest.go
Labels: kind/backport

#49916 Don't ignore errors when retrieving authentication token ID
  pkg/ext/stores/tokens/tokens.go
  pkg/ext/stores/tokens/tokens_test.go
  pkg/ext/stores/tokens/zz_token_fakes.go
Labels: area/authentication, team/collie

#51522 fix: adding safe validation for ipv6 host
  cmd/agent/main.go
Labels: team/hostbusters
