Repository rancher/rancher, pull requests merged in 2025-01, with the labels that each got.

#48450 <v2.10> Add PNI, k3s cloud manager validations and refactor for port tests
  tests/v2/validation/networking/connectivity/network_policy.go
  tests/v2/validation/networking/connectivity/network_policy_test.go
  tests/v2/validation/networking/connectivity/port_test.go
Labels: team/pit-crew

#47962 Updating local upgrade runs to report status on qase
  tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
  tests/v2/validation/pipeline/qase/testrun/main.go
  tests/v2/validation/pipeline/scripts/build_qase_auto_testrun.sh
  tests/v2/validation/pipeline/scripts/rancher_k8s_version.sh
  tests/v2/validation/upgrade/kubernetes.go
  tests/v2/validation/upgrade/workload_test.go
Labels: team/pit-crew

#48676 [main] run custodian on vpn'd node to avoid aws region errors
  tests/scripts/custodian/Dockerfile
  tests/scripts/custodian/Jenkinsfile
Labels: team/pit-crew

#48751 improving logic for qa custodian
  tests/scripts/custodian/aws.yaml
  tests/scripts/custodian/azure.yaml
Labels: team/pit-crew

#48789 Add FOSSA workflow
  .github/workflows/fossa.yml
  Dockerfile-windows.dapper
  Dockerfile.dapper
  scripts/fossa
Labels: area/pipeline

#48594 <frozen> <main> Removed UpdateClusterName from the validation tests
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/pipeline/Jenkinsfile.recurring
  tests/v2/validation/rbac/README.md
  tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
Labels: team/pit-crew

#48886 [main] P0 tests for GH-44668
  tests/v2/actions/rbac/rbac.go
  tests/v2/actions/workloads/deployment/deployment.go
  tests/v2/validation/rbac/grb/README.md
  tests/v2/validation/rbac/grb/grb.go
  tests/v2/validation/rbac/grb/grb_status_field_test.go
Labels: area/automation-test

#48807 [v2.9] Add FOSSA workflow
  .github/workflows/fossa.yml
  Dockerfile-windows.dapper
  Dockerfile.dapper
  scripts/fossa
Labels: area/pipeline

#48808 [v2.10] Add FOSSA workflow
  .github/workflows/fossa.yml
  Dockerfile-windows.dapper
  Dockerfile.dapper
  scripts/fossa
Labels: area/pipeline

#48900 [main] add a test for PNI to fleet
  tests/v2/actions/clusters/clusterconfig.go
  tests/v2/actions/clusters/clusters.go
  tests/v2/actions/fleet/fleet.go
  tests/v2/actions/kubeapi/workloads/deployments/deployments.go
  tests/v2/actions/provisioninginput/config.go
  tests/v2/validation/fleet/provisioning/networkisolation.go
  tests/v2/validation/fleet/provisioning/new_cluster_existing_gitrepo_test.go
Labels: team/pit-crew
