Repository rancher/rancher, pull requests merged in 2025-02, with the labels that each got.

#48741 <v2.10> Removed UpdateClusterName from the validation tests
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/pipeline/Jenkinsfile.recurring
  tests/v2/validation/rbac/README.md
  tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
Labels: team/pit-crew

#48743 <v2.8> Removed UpdateClusterName from the validation tests
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/pipeline/Jenkinsfile.recurring
  tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
Labels: team/pit-crew

#48742 <v2.9> Removed UpdateClusterName from the validation tests
  tests/v2/actions/provisioning/creates.go
  tests/v2/validation/clustertemplates/provisioning/clustertemplate_export_test.go
  tests/v2/validation/clustertemplates/rbac/clustertemplate_test.go
  tests/v2/validation/pipeline/Jenkinsfile.recurring
  tests/v2/validation/rbac/globalrolesv2/globalroles_v2_test.go
Labels: team/pit-crew

#48333 [2.10] Disable automatic fleet agent installation
  pkg/controllers/provisioningv2/cluster/controller.go
  pkg/controllers/provisioningv2/cluster/controller_test.go
  pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go
  pkg/controllers/provisioningv2/fleetcluster/fleetcluster_test.go
Labels: kind/enhancement, area/capi

#48981 add default userdata for harvester machine config
  tests/v2/actions/machinepools/harvester_machine_config.go
Labels: team/pit-crew

#47870 Set annotation to guest cluster VM when deleting the cluster
  pkg/controllers/provisioningv2/controllers.go
  pkg/controllers/provisioningv2/harvestercleanup/controller.go
Labels: kind/enhancement, area/capr

#44325 Fix links in Chart.yaml
  chart/Chart.yaml
Labels: status/stale, team/observability&backup

#48904 Migrate RBAC Global Role Tests
  tests/v2/actions/rbac/rbac.go
  tests/v2/validation/rbac/globalroles/README.md
  tests/v2/validation/rbac/globalroles/global_roles_test.go
  tests/v2/validation/rbac/globalroles/globalroles.go
  tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go
Labels: area/automation-test

#49105 [v2.10] Migrate RBAC Global Role Tests
  tests/v2/actions/rbac/rbac.go
  tests/v2/validation/rbac/globalroles/README.md
  tests/v2/validation/rbac/globalroles/global_roles_test.go
  tests/v2/validation/rbac/globalroles/globalroles.go
  tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go
Labels: area/automation-test

#49106 [v2.9] Migrate RBAC Global Role Tests
  tests/v2/actions/rbac/rbac.go
  tests/v2/validation/rbac/globalroles/README.md
  tests/v2/validation/rbac/globalroles/global_roles_test.go
  tests/v2/validation/rbac/globalroles/globalroles.go
  tests/v2/validation/rbac/globalroles/rbac_global_roles_test.go
Labels: area/automation-test

#48010 Add cluster name as command line argument to the node driver
  pkg/controllers/capr/machineprovision/args.go
Labels: kind/enhancement, area/machine, area/harvester, feature/node-drivers

#48755 Updates/install stackstate
  tests/v2/actions/charts/charts.go
  tests/v2/actions/charts/stackstate.go
  tests/v2/actions/observability/config.go
  tests/v2/validation/observability/README.md
  tests/v2/validation/observability/resources/10-nonha_sizing_values.yaml
  tests/v2/validation/observability/stackstate.go
  tests/v2/validation/observability/stackstate_server_test.go
  tests/v2/validation/observability/stackstate_test.go
Labels: area/automation-test, team/pit-crew
